# Generated by Django 3.2.1 on 2021-05-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="realter",
            new_name="realtor",
        ),
    ]
