# Generated by Django 3.2.1 on 2021-05-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_rename_realter_listing_realtor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ["list_date"]},
        ),
    ]
