# Generated by Django 3.2.1 on 2021-05-08 15:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Realtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "photo",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d/", verbose_name="photo"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="phone")),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                ("is_mvp", models.BooleanField(default=False, verbose_name="is mvp?")),
                (
                    "hire_date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime.now,
                        verbose_name="hire date",
                    ),
                ),
            ],
        ),
    ]
